version: "3.8"

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/docker/volumes

  backend:
    depends_on:
      - database
      - cache
    build: ./server
    ports:
      - 4003:4003

volumes:
  postgres:
  redis: