version: "3.8"

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timesheet-bot
    networks:
      - timesheet-bot

  cache:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/docker/volumes

  server:
    depends_on:
      - database
      - cache
    build: ./server
    ports:
      - 4003:4003
    networks:
      - timesheet-bot

  web:
    depends_on:
      - server
    build: ./web
    ports:
      - 3000:3000
    networks:
      - timesheet-bot

networks:
  timesheet-bot:
    driver: bridge

volumes:
  postgres:
  redis: